### ISSUE TITLE
permission denied / no such file or directory

### ISSUE THREAD

**Issue by danzelziggy** [agoes/docker-lemp-environment#1]
Hello,

Thank you for a very useful code to automate things.

Deploying new sites are having problems:

Cleanup available and enabled server blocks
cp: cannot create regular file '../images/web/sites-available/site-api.local.conf': Permission denied
sed: can't read ../images/web/sites-available/site-api.local.conf: No such file or directory
sed: can't read ../images/web/sites-available/site-api.local.conf: No such file or directory
Enabling api.local
cp: cannot create regular file '../images/web/sites-available/site-blog.local.conf': Permission denied
sed: can't read ../images/web/sites-available/site-blog.local.conf: No such file or directory
sed: can't read ../images/web/sites-available/site-blog.local.conf: No such file or directory
Enabling blog.local
cp: cannot create regular file '../images/web/sites-available/site-example.dev.conf': Permission denied
sed: can't read ../images/web/sites-available/site-example.dev.conf: No such file or directory
sed: can't read ../images/web/sites-available/site-example.dev.conf: No such file or directory
Enabling example.dev

**Comment by agoes** [comment]
Hi, sorry for the very very late response :pray: 

If you still use this, it should be fixed in the latest release : [v1.1](https://github.com/agoes/docker-lemp-environment/releases/tag/v1.1)
